%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 1064.8275227011407
Camera1.fy: 1064.8275227011407
Camera1.cx: 952.9959221051333
Camera1.cy: 556.5588796563719

# distortion parameters
Camera1.k1: -0.3926694722388618
Camera1.k2: 0.1790794694612213
Camera1.p1: 0.0016278920497310764
Camera1.p2: -0.0004312238395778432
Camera1.k3: -0.04263877898351632

Camera.width: 1920
Camera.height: 1080

Camera.newWidth: 640
Camera.newHeight: 480

# Camera frames per second 
Camera.fps: 24

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
#    data: [  0.007,  0.005, -1.000,  0.033,
#             1.000,  0.011,  0.007,  0.009,
#             0.011, -1.000, -0.005,  0.275,
#             0.000,  0.000,  0.000,  1.000]

#Novatel IMU
   data: [  -0.007, -0.005,  1.000,  0.736,
            -1.000, -0.011, -0.007, -0.451,
            0.011, -1.000, -0.005, -0.574,
            0.000,  0.000,  0.000,  1.000]


# ouster IMU
#    data: [  0.007,  0.005, -1.000,  0.033,
#             1.000,  0.011,  0.007,  0.009,
#             0.011, -1.000, -0.005,  0.275,
#             0.000,  0.000,  0.000,  1.000]



# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1e-8 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1e-8 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-8 # rad/s^1.5
IMU.AccWalk: 1e-8 # m/s^2.5
IMU.Frequency: 100.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
